### ISSUE TITLE
Создание WebAPI на базе FastAPI или на Flask

### ISSUE THREAD

**Issue by Morokenec** [SH4R1K/ArhWords#2]

**Comment by Morokenec** [comment]
На выходе изображение

`
import requests

files = {'image': open("nums.jpeg", "rb")}
r = requests.post("https://face.bubble.ru/_api/face", files=files)

with open('result.jpg', 'wb') as f:
    f.write(r.content)
`

**Comment by Meresk** [comment]
Сделал
